spring:
  application:
    name: movie-api
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5454/inventorymanagenementbd
    username: postgres
    password: postgres

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration:
      minutes: 10
  cors:
    allowed-origins: http://localhost:3000
    
logging:
  level:
    org.springframework.security: DEBUG

server:
  error:
    include-message: always