spring:
  application:
    name: inventory-management
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory-management-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: false

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration:
      minutes: 10
  cors:
    allowed-origins: http://localhost:3000
    
logging:
  level:
    org.springframework.security: DEBUG